<a href="https://colab.research.google.com/github/debanjanghosh1777-debug/AI-Assisted-Threat-Detection-Dashboard-/blob/main/SQL_Task_DG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create a simple SQL program in Python using SQLite.
Create a cybersecurity table with users, activities, threat levels and risk scores.
Use SQL commands to demonstrate ORDER BY, GROUP BY, COUNT, LIKE, CASE and LIMIT.
Show each output in table format using Pandas.

In [ ]:
import pandas as pd
import sqlite3

# Create sample cybersecurity data
data = {
    "User": ["Rahul", "Amit", "Sneha", "Ravi", "Unknown", "Neha", "Unknown"],
    "Activity": ["Login", "Failed Login", "File Access", "Password Change", "SQL Injection", "Login", "Malware Alert"],
    "Threat": ["Low", "High", "Low", "Medium", "Critical", "Low", "High"],
    "RiskScore": [20, 80, 25, 50, 95, 15, 85]
}

df = pd.DataFrame(data)

# Create database
conn = sqlite3.connect("sql_part1.db")

# Save data into SQL table
df.to_sql("security", conn, index=False)

# ORDER BY
print("ORDER BY: RiskScore from highest to lowest")
display(pd.read_sql("""
SELECT * FROM security
ORDER BY RiskScore DESC
""", conn))

# GROUP BY
print("GROUP BY: Threat levels")
display(pd.read_sql("""
SELECT Threat
FROM security
GROUP BY Threat
""", conn))

# COUNT
print("COUNT: Total records in each Threat level")
display(pd.read_sql("""
SELECT Threat, COUNT(*) AS Total
FROM security
GROUP BY Threat
""", conn))

# LIKE
print("LIKE: Activities containing Login")
display(pd.read_sql("""
SELECT * FROM security
WHERE Activity LIKE '%Login%'
""", conn))

# CASE
print("CASE: Assign Risk Category")
display(pd.read_sql("""
SELECT User, Activity, Threat, RiskScore,
CASE
    WHEN RiskScore >= 80 THEN 'Danger'
    WHEN RiskScore >= 50 THEN 'Warning'
    ELSE 'Safe'
END AS RiskCategory
FROM security
""", conn))

# LIMIT
print("LIMIT: Top 3 risky records")
display(pd.read_sql("""
SELECT * FROM security
ORDER BY RiskScore DESC
LIMIT 3
""", conn))

ORDER BY: RiskScore from highest to lowest

      User         Activity    Threat  RiskScore
0  Unknown    SQL Injection  Critical         95
1  Unknown    Malware Alert      High         85
2     Amit     Failed Login      High         80
3     Ravi  Password Change    Medium         50
4    Sneha      File Access       Low         25
5    Rahul            Login       Low         20
6     Neha            Login       Low         15

GROUP BY: Threat levels

     Threat
0  Critical
1      High
2       Low
3    Medium

COUNT: Total records in each Threat level

     Threat  Total
0  Critical      1
1      High      2
2       Low      3
3    Medium      1

LIKE: Activities containing Login

    User      Activity Threat  RiskScore
0  Rahul         Login    Low         20
1   Amit  Failed Login   High         80
2   Neha         Login    Low         15

CASE: Assign Risk Category

      User         Activity    Threat  RiskScore RiskCategory
0    Rahul            Login       Low         20         Safe
1     Amit     Failed Login      High         80       Danger
2    Sneha      File Access       Low         25         Safe
3     Ravi  Password Change    Medium         50      Warning
4  Unknown    SQL Injection  Critical         95       Danger
5     Neha            Login       Low         15         Safe
6  Unknown    Malware Alert      High         85       Danger

LIMIT: Top 3 risky records

      User       Activity    Threat  RiskScore
0  Unknown  SQL Injection  Critical         95
1  Unknown  Malware Alert      High         85
2     Amit   Failed Login      High         80

#Create a simple SQL program in Python using SQLite.
Create two tables named users and alerts.
Use SQL commands to demonstrate WHERE clause, unique values, duplicate records, removing duplicates, INNER JOIN, LEFT JOIN and RIGHT JOIN.
Show each output in table format using Pandas.

In [ ]:
import pandas as pd
import sqlite3

# Create users data
users_data = {
    "UserID": [1, 2, 3, 4, 6],
    "UserName": ["Rahul", "Amit", "Sneha", "Ravi", "Neha"],
    "Department": ["IT", "Finance", "HR", "IT", "Marketing"]
}

# Create alerts data
alerts_data = {
    "UserID": [1, 2, 2, 3, 4, 5],
    "Activity": ["Login", "Failed Login", "Failed Login", "File Access", "Malware Alert", "SQL Injection"],
    "Threat": ["Low", "High", "High", "Low", "Medium", "Critical"]
}

users = pd.DataFrame(users_data)
alerts = pd.DataFrame(alerts_data)

# Create database
conn = sqlite3.connect("sql_part2.db")

# Save data into SQL tables
users.to_sql("users", conn, index=False)
alerts.to_sql("alerts", conn, index=False)

# WHERE clause
print("WHERE: Show only High threats")
display(pd.read_sql("""
SELECT * FROM alerts
WHERE Threat = 'High'
""", conn))

# UNIQUE values
print("UNIQUE: Show unique threat values")
display(pd.read_sql("""
SELECT DISTINCT Threat
FROM alerts
""", conn))

# Find duplicate records
print("Duplicate Records")
display(pd.read_sql("""
SELECT UserID, Activity, Threat, COUNT(*) AS Total
FROM alerts
GROUP BY UserID, Activity, Threat
HAVING COUNT(*) > 1
""", conn))

# Remove duplicate records from output
print("Remove Duplicates")
display(pd.read_sql("""
SELECT DISTINCT *
FROM alerts
""", conn))

# INNER JOIN
print("INNER JOIN")
display(pd.read_sql("""
SELECT users.UserID, users.UserName, users.Department, alerts.Activity, alerts.Threat
FROM users
INNER JOIN alerts
ON users.UserID = alerts.UserID
""", conn))

# LEFT JOIN
print("LEFT JOIN")
display(pd.read_sql("""
SELECT users.UserID, users.UserName, users.Department, alerts.Activity, alerts.Threat
FROM users
LEFT JOIN alerts
ON users.UserID = alerts.UserID
""", conn))

# RIGHT JOIN style output
print("RIGHT JOIN")
display(pd.read_sql("""
SELECT alerts.UserID, users.UserName, users.Department, alerts.Activity, alerts.Threat
FROM alerts
LEFT JOIN users
ON alerts.UserID = users.UserID
""", conn))

WHERE: Show only High threats

   UserID      Activity Threat
0       2  Failed Login   High
1       2  Failed Login   High

UNIQUE: Show unique threat values

     Threat
0       Low
1      High
2    Medium
3  Critical

Duplicate Records

   UserID      Activity Threat  Total
0       2  Failed Login   High      2

Remove Duplicates

   UserID       Activity    Threat
0       1          Login       Low
1       2   Failed Login      High
2       3    File Access       Low
3       4  Malware Alert    Medium
4       5  SQL Injection  Critical

INNER JOIN

   UserID UserName Department       Activity  Threat
0       1    Rahul         IT          Login     Low
1       2     Amit    Finance   Failed Login    High
2       2     Amit    Finance   Failed Login    High
3       3    Sneha         HR    File Access     Low
4       4     Ravi         IT  Malware Alert  Medium

LEFT JOIN

   UserID UserName Department       Activity  Threat
0       1    Rahul         IT          Login     Low
1       2     Amit    Finance   Failed Login    High
2       2     Amit    Finance   Failed Login    High
3       3    Sneha         HR    File Access     Low
4       4     Ravi         IT  Malware Alert  Medium
5       6     Neha  Marketing           None    None

RIGHT JOIN

   UserID UserName Department       Activity    Threat
0       1    Rahul         IT          Login       Low
1       2     Amit    Finance   Failed Login      High
2       2     Amit    Finance   Failed Login      High
3       3    Sneha         HR    File Access       Low
4       4     Ravi         IT  Malware Alert    Medium
5       5     None       None  SQL Injection  Critical